---
- name: Zabbix agent2 installation on CentOS 7
  hosts: all
  vars:
    server: X.X.X.X
  tasks:
  - name: Import a key from a url
    ansible.builtin.rpm_key:
      state: present
      key: http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX
      
  - name: Install Zabbix repository configuration
    yum:
      name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
      state: present
      
  - name: add zabbix repository
    yum_repository:
      name: Zabbix Official Repository - $basearch
      description: Zabbix Official Repository
      file: zabbix
      baseurl: http://repo.zabbix.com/zabbix/5.0/rhel/7/$basearch/
      gpgcheck: yes
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
      enabled: yes
  
  - name: Install the 'zabbix-agent2' package
    yum:
      name: "zabbix-agent2"
      state: present
      
  - name: Insert/Update zabbix_agent2 configuration
    blockinfile:
      path: /etc/zabbix/zabbix_agent2.conf
      block: |
        PidFile=/var/run/zabbix/zabbix_agent2.pid
        LogFile=/var/log/zabbix/zabbix_agent2.log
        LogFileSize=0
        Server={{server}}
        ServerActive={{server}}
        Hostname=Zabbix server
        Include=/etc/zabbix/zabbix_agent2.d/*.conf
        ControlSocket=/tmp/agent.sock
        Plugins.Smart.Timeout=30
                    
  - name: configure zabbix ceph module
    copy:
         content: "Plugins.Ceph.InsecureSkipVerify=true"
         dest: "/etc/zabbix/zabbix_agent2.d/ceph.conf"
  
  - name: Ensure zabbix-agent2 is at the latest version
    ansible.builtin.yum:
      name: zabbix-agent2
      state: latest
    notify:
    - Restart zabbix-agent2
    
  - name: Flush handlers
    meta: flush_handlers
  - name: Ensure that zabbix-agent2 is started
    ansible.builtin.service:
      name: zabbix-agent2
      state: started
      
  - name: Enable service zabbix-agent2, and not touch the state
    ansible.builtin.service:
      name: zabbix-agent2
      enabled: yes
      
  handlers:
    - name: Restart zabbix-agent2
      ansible.builtin.service:
        name: zabbix-agent2
        state: restarted
